webida/webida-client

apps/ide/src/plugins/codeeditor/plugin.json
[example of plugin.json for plugin.xml]
{
"name": "xmleditor",
"description": "XML editor",
"version": "0.1.0",
"requirement": "webida.common.editors",
"extensions" : {
"webida.common.editors:editor" : {
"name" : "XML editor",
"fileValueRequired" : true,
"handledFileExt" : [],
"handledMimeTypes" : [],
"handledFileNames" : [ "plugin.xml" ],
"unhandledFileExt" : [],
"unhandledMimeTypes" : []
}
}
}
=> [BUGFIX] "handledFileNames" spec. added to webida.common.editors:editor extension point

apps/ide/src/plugins/project-wizard/lib/util.js, apps/ide/src/plugins/project-wizard/main.js, apps/ide/src/plugins/project-wizard/plugin.json, apps/ide/src/plugins/webida.ide.project-management.run/delegator.js, apps/ide/src/plugins/webida.ide.project-management.run/plugin.json, apps/ide/src/plugins/webida.ide.project-management.run/run-configuration-manager.js, apps/ide/src/plugins/webida.ide.project-management.run/view-controller.js, common/src/webida/app.js
- [BUGFIX] fix run configuration bugs when file or directory changed
- [FEATURE] let project wizard use new run configurator
- [FEATURE] add a commonly used method (getWorkspaceInfo) to app.js
- [FEATURE] use default empty delegator when there isn't any delegators for its run type
- [FEATURE] be invisible any run type extension set 'hidden' property on in run configuration popup
- [BUGFIX] minor bug fix
=> Add new run configuration features and fix bug

common/src/webida/plugins/git/gitview-log.js
[BUGFIX] (ODP-3207) hide authentication information in git log message
[BUGFIX] (ODP-43) recognize actual url address in git log message
=> [BUGFIX] fix incorrect git log messages

common/src/webida/webida-0.3.js
* deleteMyApps() api bug : When calling deleteApp() in deleteMyApps() api, appid should be passed instead of domain.
* setAppInfo() api bug : callback argument is undefined if srcurl argument is omitted.
Signed-off-by: Sangjin Kim <sangjin3.kim@samsung.com>
=> [BUGFIX] deleteMyApps(), setAppInfo() api bug.

apps/site/src/js/main.js
[DESC.]
This change fixes to show correct error message for duplicate account by matching with regular expression.
Currently, the error is shown just as "Unknown".
=> [BUGFIX] Fix to show correct error message for duplicate account

apps/dashboard/index.html
[DESC.]
Description is not available because workspace information is not stored into separate storage like a file. Workspace is just a directory now, so requesting workspace description to user is useless and confusing.
=> [TASK] Remove description user input when creating a workspace

common/src/webida/msg.js, common/src/webida/webida-0.3.js
* webida-0.3.js can accept host env vars in query string. It's useful to load client code in local web server for testing.
* msg.js loads socket.io from lib directory not from connection server. It can share socket.io library with other modules.
=> [TASK] webida-0.3.js accepts host env vars in query string

apps/ide/src/plugins/webida.ide.project-management.run/plugin.js, common/src/webida/plugins/workbench/command-system/toolbar.js
[DESC.] Toolbar module changed to send index number as "-1" to each plugin that implement menu extention point once the toolbar icon clicked.
=> [BUGFIX] Fix #155 (ODP-456)

common/src/webida/plugins/workbench/command-system/toolbar.js
Currently, toolbar icon has a class name like ".dijit_form_Button_0_wticons" for 'New File'.
Amd if a user wants to override the icon for it, he wrote a rule like ".dijit_form_Button_0_wticons { his new file image } !important".
But the index can be changed by adding extension toolbars.
For example, 'New Project' has index 0 and 'New File' has index 1. In that case, he should modify above rule to ".dijit_form_Button_1_wticons { his new file image } !important".
So, I changed the unique class selector derived from menu item path like ".__File__New__File_wticons".
=> [TASK] Use unique class selector for toolbar icon

common/src/webida/plugins/editors/workbench-panels.js
when a dirty file exists, dialog boxes between File>Close and File>Quit are different.
=> [enhancement] #205 Quit menu change when a dirty file exist

common/src/webida/plugins/workbench/command-system/toolbar.js
[DESC.]
This change shows a tooltip like "New (Alt+N)" from "New/Alt+N" in the toolbar.
Also this change adds 'iconClass' property for toolbar icon.
If it is set, it precedes 'icons' property.
For example, if an extension specifies 'iconClass' as "extesion123-toolbar-new" and it defines a rule for the class "extesion123-toolbar-new" in its CSS, an extension can use sprite image in the toolbar by 'background-image' and 'background-position'.
=> [TASK] Support a class and change shortcut tooltip for toolbar icon

apps/ide/src/plugins/webida.editor.code-editor/CodeEditorViewer.js, apps/ide/src/plugins/webida.editor.text-editor/TextEditorViewer.js
[DESC.] After re-sizing by splitter, pressing maximize button causes no re-sizing of the editor. We fixed this bug.
=> [BUGFIX] #162 Editor re-sizing related refactoring (Bug fix)

common/src/webida/plugins/workbench/views-controller.js
[DESC.] In '#317 Editors are not re-sized for size changes within the editor area', duplicated operation is removed.
=> [BUGFIX] #162 Editor resizing related refactoring (bug fix)

common/src/webida/FSCache-0.1.js, common/src/webida/webida-0.3.js
1) support reading binary file
Current FileSystem.readFile() API always assumes text file and uses XMLHttpRequest.responseText.
It's required to set XHR.responseType and use XHR.response for reading binary file.
This added additional argument responseType to readFile() and caller can determine the file type.
2) add fallback for the failure of getting cookie
This change adds fallback when the cookie value for Auth host is empty.
The cookie might not be set when a resource is cached and served by Proxy server.
So in that case, I try to get Auth host by window.location value.
And this change also adds a step for getting webidaHost.
Currently, if the cookie is not set, /isloggedin call is requested to 'https://webiga.org'.
So this adds a step to get a host by window.location value.
Change-Id: …
=> [FEATURE] 1) support reading binary file. 2) add fallback for no cookie

apps/ide/src/plugins/webida.editor.code-editor/CodeEditorViewer.js, apps/ide/src/plugins/webida.editor.text-editor/TextEditorViewer.js
emmet was using getMode of editor viewers and TextEditorViewer didn't provide the API.
=> [BUGFIX] Move getMode from CodeEditorViewer to TextEditorViewer #279

apps/ide/src/plugins/webida.editor.example.multi-viewer/MultiViewerExampleEditorPart.js
[DESC.] Shortcut key not working on "MultiViewerExampleEditor's source editor tab " problem is fixed. MultiViewerExampleEditor should initialize listeners as CodeEditorPart and TextEditorPart.
=> [BUGFIX] #358 Shortcut key not working on "MultiViewerExampleEditor"

common/src/webida/plugins/workspace/Node.js
Fixed that A file with space in file's name is not moved and copied at the workspace
=> [BUGFIX] #374 Cannot move or copy a file with a space on its name.

common/src/webida/plugins/editors/workbench-panels.js
=> [ENHANCEMENT] #327 Quit does not work when a user access IDE directly

common/src/webida/plugins/workspace/plugin.js
[DESC.] Workspace view flickers when selecting a new resource while last
selected resource is not shown by scrolling.  Workspace view tree shows
last selected node as default behavior of focus event. This change
ignores focus event because that's the usual way of handling focus in
usual file trees such as Windows Explorer, Chrome DevTools, Eclipse,
etc.
Change-Id: Ia02990621c4001b3e9254925809a3ee6c34ce9c7
Signed-off-by: WooYoung Cho <wy1.cho@samsung.com>
=> [BUGFIX] #404 Fix workspace view flickers

apps/deploy/plugins/paas-webida/plugin.js, apps/ide/src/plugins/webida.preference/layout/preferences-tree.html, apps/ide/src/plugins/webida.preference/pages/SimplePage.js, apps/ide/src/plugins/webida.preference/preference-manager.js, apps/ide/src/plugins/webida.preference/preference-store.js, apps/ide/src/plugins/webida.preference/style/style.css, apps/ide/src/plugins/webida.preference/tree-view-controller.js, apps/ide/src/plugins/webida.preference/view-controller.js, common/src/webida/plugins/git/plugin.json
- If parent is not exist in the same scope, child nodes will be shown below the closest exist ancestor node.
- `visible` property of the `webida.preference:pages` extension can be replaced with empty scope array `scope: []`
- improve validation messaging
- cannot change selection of tree item until sub-page is loaded completely
=> [IMPROVEMENT] improvement on preference plugin

common/src/webida/plugins/editors/menu-items.js
[DESC.] Split view behavior is changed.
=> [BUGFIX](#432) The action of 'Editor Tab Split' runs contrary

apps/ide/src/plugins/webida.editor.code-editor/CodeEditorViewer.js, apps/ide/src/plugins/webida.editor.text-editor/TextEditorViewer.js
[DESC.] Related to viewer.focus()
=> [BUGFIX](#517)FInd/replace dialogs are closed immediately after opening.

apps/ide/src/plugins/webida.terminal/plugin.js
[DESC.]
This commit shows 'Terminal' view in 'Select View from List'.
To do this, workbench#registToViewFocusList() should be called explicitly.
I hope future 'Select View from List' will work only based on plugin.json's view extension information.
Change-Id: I83f774fd65d1e6ecee5dbe28547e807e742b3174
Signed-off-by: KangHo Kim <kh5325.kim@samsung.com>
=> [TASK] Show 'Terminal' view in 'Select View from List'

common/src/webida/util/genetic.js
Without explicit 'var' keyword, prop will be a global variable.
=> [BUGFIX] Make 'prop' to be a local variable.

common/src/webida/FSCache-0.1.js
- If the workspace is refreshed after creating a file or a directory using a terminal, the file or the directory isnot shown.
- fix it inserting a delimiter in dir cache.
=> [BUGFIX] A root directory is not refresh in a workspace.

bower.json
Note that file named as 'aux.js' is not allowed on windows.
=> [TASK] Use updated calcium, whose aux.js is renamed to helper.js.

apps/ide/src/styles/css/webida-base.css
[DESC.] declear for font-family in css
please don't make regression bug.
It was modified in the past, but it was returned.
* https://github.com/webida/webida-client/commit/a68bb73debd6073db45b7e820c2f6aabefb8b1f0
Signed-off-by: ChangHyun Lee <leechwin.lee@samsung.com>
=> [BUGFIX] fix "Nanum Gothic Coding" font can not apply

apps/ide/src/plugins/webida.preference/preference-service-factory.js, apps/ide/src/plugins/webida.preference/services/preference-service.js, apps/ide/src/plugins/webida.preference/services/project-preference-service.js
An error occurred while getting a service instance scoped as a project because there is no
project scope. So modify code to create a project scope before creating instance of a service.
In addition, it modifies the instance creation part of the service.
Change a second parameter of .apply as an array. It is because must be an array.
And instead of referring to non-existent 'initialized' property to correct to call a 'initialize' function.
And also change the reference to the global self with reference to the local self.
It is because there is no global self.
Signed-off-by: Jugwan Kim <jugwan@webida.org>
=> [BUGFIX] fix a bug that cannot get a service instance scoped as project

apps/ide/src/plugins/webida.editor.code-editor/CodeEditorViewer.js
Currently when we write "this.", property list does not automatically appear. This patch enables auto-hint for this keyword just like other expressions.
=> [IMPROVEMENT] Auto-hint properties of this keyword.

apps/ide/src/plugins/webida.editor.code-editor/plugin.json, apps/ide/src/plugins/webida.editor.text-editor/plugin.json, apps/ide/src/plugins/webida.preference/preference-manager.js
[DESC.]
- For drawing tree nicely, the pages in preferences should be sorted by its hierarchy.
- change page id to its displayed name ('texteditor' -> 'editor') for sorting
=> [BUGFIX] solve unexpected rendered tree hierarchies in preference dialog

common/src/webida/util/locale.js
[DESC.]
- If it runs with enumerable option, top-down converting on menu items that has hierarchy may occurres an error.
=> [BUGFIX] set `alternateLabel` property in `convertMenuItem` method with no enumerable option

bower.json
[DESC.]
This commit allows us to use the updated codemirror through bower.
* This version has a new option "lineSeparator" which makes #707 by @hwshim work properly.
* The problem of webida/codemirror#64 does not occur.
* It has a minor problem of overlapping hints ( webida/codemirror#66 ), which will be fixed soon.
=> [TASK] Use codemirror updated to 5.8.0.

apps/ide/src/plugins/webida.editor.code-editor.content-assist.calcium/calcium.js
[DESC.] Close the argument hints when editors get blurred.
Additionally, temporal tool-tip will start to fade out when editors get blurred or scrolled.
=> [BUGFIX] [calcium] Close argument hints on blur (#585)

common/src/webida/webida-0.3.js
[DESC.] File download does not work when editor have a dirty file. That is caused by using location.href for download. We changed location.href using to using window.open().
=> [BUGFIX](#705)File download does not work when editor have a dirty file

apps/ide/src/plugins/webida.editor.text-editor/preferences/preference-editor.js
* Missing underlines for same words when double-clicked (#749)
* Missing active line styling (#755)
=> [BUGFIX] (#749, #755) Missing preference problem for TextEditor 

apps/ide/src/plugins/project-configurator/projectConfigurator.js
- If the project.json file was corrupted, rewrite the file with only known information.
=> [BUGFIX] (#606) Handle JSON parse error of project.json in project configurator

common/src/webida/plugins/git/git-commands-diff.js
- preferences method changed to 'setValues' instead of 'updateValue'
=> [BUGFIX](#765)'Line of Context' is not closed(Git)

Gruntfile.js, package.json
[FEATURE] #760 modify Gruntfile.js for building on less files and related resources
[DESC.]
- add new grunt task 'themeBuild' that generate and run tasks related with theme resourcees automatically
- With `grunt themeBuild`(build all), `grunt themeBuild:less`(build less file only), `grunt themeBuild:resource`(build(copy) resources only), you can build theme.
- add new grunt task 'watch' for theme development
- Run this task with the `grunt watch` command
=> [FEATURE] #760 modify Gruntfile.js for building on less files and related resources

apps/ide/src/index.html, common/src/webida/app-config.js, common/src/webida/app.js, common/src/webida/theme.js
#760 
[DESC.]
- check current theme(set in app-config) and load proper css and favicon file
- Simplify `ide.startup` method
- following code conventions
=> [FEATURE] #760 load dynamically proper theme.css file

common/src/webida/app-config.js, common/src/webida/config-loader.js
#754 
[DESC.]
- In jquery, synchronous ajax query was deprecated because of its bad effects to UX.
- So our Synchronous XMLHttpRequest in `app-config` is replaced with "loader plugin of Require.js" for loading server-side configs.
- It is more clear way to get configurations than before.
- This new `config-loader` loader plugin enables that `app-config` module can return value asynchronously.
=> [IMPROVEMENT] #754 Synchronous XMLHttpRequest on the main thread is deprecated (jQuery)

apps/ide/src/plugins/webida.editor.code-editor.content-assist.calcium/CalciumControl.js, apps/ide/src/plugins/webida.editor.code-editor.content-assist.tern/TernControl.js, apps/ide/src/plugins/webida.editor.code-editor/CodeEditorViewer.js
[DESC.]
* Now, each of tern and calcium executes 'closeArgHints' command at the beginning of its 'completion' command.
* Therefore, the completion list dialog and argument hint do not overlap as shown in the screenshot of webida/codemirror#66.
* Originally the same issue was resolved by adding custom option 'onBeforeShowHint' to codemirror, which required patching codemirror. Using the approach in this commit, we do not need to patch codemirror anymore. Additionally, the option 'onBeforeShowHint' is useless and removed from CodeEditorViewer.js.
* Sorry for the many irrelevant changes, deleting blanks.
=> [BUGFIX] Close argument hint before showing completion list.

apps/ide/src/plugins/webida.ide.project-management.run.java/layout/java-run-configuration.html, apps/ide/src/plugins/webida.ide.project-management.run.java/nls/en-us/resource.js, apps/ide/src/plugins/webida.ide.project-management.run.java/nls/resource.js, apps/ide/src/plugins/webida.ide.project-management.run.java/plugin.js, apps/ide/src/plugins/webida.ide.project-management.run/README.md, apps/ide/src/plugins/webida.ide.project-management.run/default-view-controller.js
- Use `ValidationTextBox` and its properties(regExp, invalidMessage)
- Use `dijit/form/Form`'s validate() function for validation on whole form
- add topic and usage descriptions
- This problem caused by the previous PR(#817).
- For validation on async item (e.g. project), using dojo.store implementations, `Observable` and `Memory`
=> Issue#375 improvements, documentation and bugfix on run configuration plugin

common/src/webida/plugins/workspace/Node.js
[DESC.] If the name of selected file/directory contains no '.', then no string is selected. We changed it to select entire string.
=> [BUGFIX](#763)Cannot select name of directory to rename.

apps/ide/src/plugins/webida.editor.code-editor.content-assist.tern/js-hint-server.js, apps/ide/src/plugins/webida.editor.code-editor.content-assist.tern/tern-plugin-dojojs.js, apps/ide/src/plugins/webida.editor.code-editor.content-assist.tern/tern-server-starter.js, bower.json
[DESC.]
For each of the commits, 
1) This commit makes tern use correct base url in dojojs plugin.
2) A simple refactoring
3) While tern uses relative paths, file-server and others should use absolute paths.
Therefore, I applied getAbsPath for path data coming from tern,
and applied getRelPath for path data going into tern.
4) I needed to modify tern to resolve #808. This commit updates the commit id of tern in bower.json
=> [TASK] Fix path problems caused by updated tern

bower.json
[DESC.] #847 was caused by tern that tries to analyze a file whose `text` value is `null`.
So, I fixed tern so that it does not analyze such invalid files.
=> [TASK] Use tern fixed for #847.

apps/ide/src/plugins/webida.editor.code-editor.content-assist.tern/js-hint-server.js, bower.json
[DESC.]
- Since completion request can contain absolute paths data in `body.files`, we convert them to relative paths.
- tern is additionally fixed for #847.
=> [BUGFIX] Additional path conversion in request to tern.

common/src/webida/plugins/fs-commands/fs-commands.js, common/src/webida/plugins/fs-commands/layer/searchFilesForm.html
- replace initializing dojo widget with programmatic way
- change markup of the template
- I could not find what is the real reason of this problem. The strongest suspects are `ComboBox` and "LAYOUT" (including its style) of the template.
=> [BUGFIX] (#854) Prevent from chrome freezing when 'Find in Files' runs

apps/ide/src/plugins/webida.editor.code-editor/content-assist/assist.js, common/src/webida/webida-0.3.js
[DESC.]
- add an option (e.g. mayNotExist) to the readFile API
- If this options is true, server will response with 204(No Conent) status code in error case of 404.
=> [BUGFIX] (#865) Too many 404 errors for tern requests

apps/ide/src/plugins/webida.ide.project-management.run/view-controller.js, apps/ide/src/plugins/webida.preference/preference-manager.js, apps/ide/src/plugins/webida.preference/preference-store.js, apps/ide/src/plugins/webida.preference/view-controller.js
- Undo all changes while closing preference dialog
-  If there's no changes, the execution of 'Run' button will not produce the 'successful save' message.
Related issue #851, #863
=> [BUGFIX] Bug fixes on run configuration and preference dialog

apps/ide/src/plugins/webida.perspective.example1/plugin.js, apps/ide/src/plugins/webida.perspective.example1/plugin.json, common/src/webida/plugins/workbench/plugin.json, common/src/webida/plugins/workbench/views-controller.js, common/src/webida/plugins/workbench/workbench.html
[DESC.] We added simple perspective selection drop-down menu at the top-right corner. Every extensions which extends 'org.eclipse.ui.perspectives' extension point are listed. If there is no plugin which extends 'org.eclipse.ui.perspectives' extension point, then that drop-down menu is not given.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/webida/webida-client/904)
=> [FEATURE](#902) Perspective selection UI
