webida/webida-client

README.md

[TASK] Readme.md added

---

Gruntfile.js

[DESC.] paths of src of jshint have been changed.

[BUGFIX] fixed src paths for jshint in Gruntfile.js

---

Gruntfile.js

[DESC.] re-arranged path of src which should be checkec.

[BUGFIX]changed src path and excluded fils

---

apps/ide/src/dojoConfig.js

[BUGFIX] Failed to open shortcut key list dialog (WTC-3294)

---

apps/ide/src/dojoConfig.js
apps/ide/src/dojoConfigforDeploy.js

[BUGFIX] Apply previous bugfix (WTC-3294) to dojoConfigforDeploy.js too

---

common/src/webida/FSCache-0.1.js

...n refresh hierarchy.
[DESC]

(Minor) Renaming two directories (commons, externals) and moving a directory (ProjectWizard-templates)

---

apps/ide/src/plugins/help/help-commands.js

[BUGFIX] Fixing WTC-3295 (Unable to open the About dialog)

---

common/src/webida/FSCache-0.1.js
common/src/webida/plugins/editors/plugin.js
common/src/webida/plugins/workspace/plugin.js
common/src/webida/util/loadCSSList.js
common/src/webida/widgets/views/viewcontainer.js
common/src/webida/widgets/views/viewmanager.js

[TASK] Applying changes applied to library but not to webida-client

---

common/src/webida/plugins/workspace/Node.js
common/src/webida/plugins/workspace/plugin.js

[TASK] Exposing 'upload' API of workspace for UIP20

---

apps/ide/src/plugins/codeeditor/plugin.js
common/src/webida/plugins/editors/plugin.js

[BUGFIX] [ODP-246], [Editor] Remove implicit transform of uploaded file

---

apps/ide/src/plugins/webida.common.workspace/config.json
common/src/webida/plugins/editors/plugin.js
common/src/webida/plugins/fs-commands/fs-commands.js
common/src/webida/plugins/fs-commands/plugin.js
common/src/webida/plugins/fs-commands/plugin.json

[FEATURE] (ODP-224) Open file with multiple editors

---

Gruntfile.js
package.json

[DESC.] fixed Gruntfile for jshint. (path of src)

[TASK] fixed Gruntfile for jshint

---

apps/ide/src/plugins/codeeditor/search-addon.js

[BUGFIX] [ODP-53] [Editor] Removing search highlights

---

apps/ide/src/plugins/webida.ide.project-management.run/delegator.js
apps/ide/src/plugins/webida.ide.project-management.run/plugin.js
apps/ide/src/plugins/webida.ide.project-management.run/run-configuration-manager.js
apps/ide/src/plugins/webida.ide.project-management.run/view-controller.js

- run configuration tree changed when run configuration item is changed
- indicate "latest run"
- apply run configurations edited directly on file(workspace.json)
- fix the action of "run" (top & context) menu
- fix (top & context) menu's run list sorting argolithm
- etc.

[BUXFIX] fix bugs related with the run configuration UI

---

apps/ide/src/plugins/project-wizard/plugin.json
apps/ide/src/plugins/webida.ide.project-management.run/delegator.js
apps/ide/src/plugins/webida.ide.project-management.run/run-configuration-manager.js
apps/ide/src/plugins/webida.ide.project-management.run/view-controller.js
common/src/webida/app.js

- fix type errors
- add validation on saving
- supplement with getWorkspaceInfo() method

Fix some bugs and add supplements on run configuration plugin

---

apps/ide/src/plugins/codeeditor/codemirror.js

[TASK] Support for XML syntax highlight

---

apps/dashboard/menus/myworkspace/app.js
apps/ide/src/plugins/webida.ide.project-management.run/default-run-configuration.html
apps/ide/src/plugins/webida.ide.project-management.run/plugin.js
apps/ide/src/plugins/webida.ide.project-management.run/run-configuration-manager.js
apps/ide/src/plugins/webida.ide.project-management.run/style.css
apps/ide/src/plugins/webida.ide.project-management.run/view-controller.js
common/src/webida/plugins/editors/plugin.js
common/src/webida/plugins/fs-commands/plugin.js

- [BUGFIX] (ODP-327) fix a bug that does not save setting file when you press the "Apply" button
- [TASK] modify the design of the run configuration popup

Bug fixed and design updated on run configuration popup

---

apps/ide/src/plugins/webida.ide.project-management.run/delegator.js

[DESC] Run the other configurators In the same window

[BUGFIX] fix arg of window open

---

apps/ide/src/plugins/webida.editor.test-editor/test-case/open_with_test_case.test
apps/ide/src/plugins/webida.editor.test-editor/test-case/other_name.test

[BUGFIX] Test Editor TC example changed

---

apps/ide/ProjectWizard-templates/java/simple/spec.json
apps/ide/src/plugins/plugin-settings.json
apps/ide/src/plugins/project-wizard/lib/util.js
apps/ide/src/plugins/project-wizard/main.js
apps/ide/src/plugins/webida.editor.test-editor/plugin.js
apps/ide/src/plugins/webida.ide.project-management.run.java/java-run-configuration.html
apps/ide/src/plugins/webida.ide.project-management.run.java/plugin.js
apps/ide/src/plugins/webida.ide.project-management.run.java/plugin.json
common/src/webida/util/logger/appenders/file-appender.js
common/src/webida/util/logger/config/client-config.js
common/src/webida/util/logger/config/server-config.js
common/src/webida/util/logger/logger-client.js
common/src/webida/util/logger/logger-interface.js
common/src/webida/util/logger/logger-server.js

[DESC.] Add a Java run configuration plugin, Add java simple template, change project wizard plugin to handle the java project

Java Enable

---

apps/ide/src/plugins/webida.ide.project-management.run/view-controller.js

[DESC] onload to use extension

[BUGFIX] fix onLoad in Configurations Dialog

---

apps/ide/src/plugins/webida.ide.project-management.run/delegator.js
apps/ide/src/plugins/webida.ide.project-management.run/plugin.js
apps/ide/src/plugins/webida.ide.project-management.run/view-controller.js

- and fix some jshint's warnings

[TASK] Give consistency to the toast messages of run configuration

---

apps/ide/src/plugins/codeeditor/addon/overview-ruler/overview-ruler.js
apps/ide/src/plugins/codeeditor/codemirror.js
apps/ide/src/plugins/codeeditor/plugin.js
apps/ide/src/plugins/codeeditor/search-addon.js

[FEATURE] [Overview Ruler] Overview Ruler base upload.

---

TestRunner.html
apps/ide/src/plugins/webida.editor.test-editor/plugin.js
apps/ide/src/plugins/webida.editor.test-editor/unit-test.js
apps/ide/src/unit-test.html
external/src/qunit/qunit-1.18.0.css
external/src/qunit/qunit-1.18.0.js
external/src/qunit/qunit-composite.css
external/src/qunit/qunit-composite.js

1) Install Test Framework Qunit
2) Write sample TC code

[Feature] (ODP-405) Support for Unit Test Environment

---

apps/ide/src/plugins/webida.editor.test-editor/unit-test.js

[BUGFIX] Module path corrected

---

apps/ide/src/plugins/webida.editor.test-editor/unit-test.js

[BUGFIX] Path corrected

---

apps/ide/src/plugins/webida.editor.test-editor/unit-test.js

[DESC.] (See ODP-405) Support for Unit Test Environment

[TASK] Sample Test Case for TestEditor plug-in

---

apps/ide/src/plugins/codeeditor/themes/webida-dark.css
common/src/webida/plugins/editors/plugin.js

[BUGFIX] (ODP-336) Reload dialog malfunction

---

apps/ide/src/plugins/webida.ide.project-management.run/plugin.js

[DESC] 'Run configurations' to 'Run Configurations'

[BUGFIX] fix the word

---

common/src/webida/plugins/editors/README.md
common/src/webida/plugins/editors/plugin.json
common/src/webida/util/logger/config/client-config.js

[TASK] Client logger config for all types added

---

common/src/webida/plugins/editors/viable-menu-items.js
common/src/webida/widgets/dialogs/file-selection/FileSelDlg2States.js

Change-Id: I2e1e7c9a5a424623ff01bc2018e78b61baf5739d
Signed-off-by: GyeongSeok Seo <gyseok.seo@samsung.com>

[BUGFIX] Fix the incorrect operation in file selection dialog

---

apps/desktop/script/js/main.js

[DESC.]
This change fixes to show correct error message for changing password.
Currently, IDE shows always the same message "The old password is not correct".

[BUGFIX] Fix to show correct error message for changing password

---

apps/ide/src/plugins/webida.ide.project-management.run/delegator.js

[BUGFIX] fix no search debug extension

---

apps/ide/src/plugins/webida.ide.project-management.run/run-configuration-manager.js
apps/site/pages/home.html

[DESC.]
prevent to load configuration file(workspace.json) while the file is being written.

 [BUGFIX] (ODP-450) fix the problem on setting run configuration in background (e.g. creating new project with a default run conf)

---

apps/ide/src/plugins/codeeditor/CodeEditor.js
apps/ide/src/plugins/codeeditor/plugin.json
apps/ide/src/plugins/plugin-settings.json
common/src/webida/plugins/webida.editor.text-editor/TextEditor.js

[BUGFIX] TextEditor and CodeEditor fixed

---

common/src/webida/plugins/git/git-commands.js
common/src/webida/plugins/git/git-core.js
common/src/webida/plugins/git/gitview-log.js
common/src/webida/plugins/git/layer/commit.html
common/src/webida/plugins/git/layer/fetch.html
common/src/webida/plugins/git/layer/pull.html
common/src/webida/plugins/git/layer/runcommand.html
common/src/webida/plugins/git/plugin.js
common/src/webida/plugins/git/plugin.json

* add 'Run Git Command'
* fix wrong labels for refspecs in pull/fetch dialogs
* better escaping when logging git result

[FEATURE] add 'Run Git Command'. fix some wrong messages in git plugin.

---

apps/ide/src/plugins/codeeditor/preference-appearance.js

[BUGFIX] Preference Dialog display bug fixed

---

apps/ide/src/plugins/plugin-settings.json
apps/ide/src/plugins/webida.editor.test-editor/TestEditor.js
apps/ide/src/plugins/webida.editor.test-editor/plugin.js
apps/ide/src/plugins/webida.editor.test-editor/plugin.json

[BUGFIX] webida.editor.test-editor's TestEditor class added

---

apps/ide/src/plugins/webida.editor.text-editor/TextEditorContext.js
apps/ide/src/plugins/webida.editor.text-editor/TextEditorPart.js
apps/ide/src/plugins/webida.editor.text-editor/search-addon.js

[DESC.] Incorrect editor re-sizing after opening search dialog is fixed.

[BUGFIX](ODP-458) Incorrect editor re-sizing (when search).

---

apps/ide/src/plugins/webida.ide.project-management.run.java/plugin.js
apps/ide/src/plugins/webida.ide.project-management.run/delegator.js
apps/ide/src/plugins/webida.ide.project-management.run/run-configuration-manager.js
apps/ide/src/plugins/webida.ide.project-management.run/style.css
apps/ide/src/plugins/webida.ide.project-management.run/view-controller.js

[BUGFIX] (ODP-454) fix the bug that unsaved configuration remain afte…
[IMPROVEMENT] make 'view-controller' to deal with lifecycle (creating and removing) on child widgets for each run configuration

Bug fix and improvement on run configuration

---

apps/ide/src/plugins/webida.ide.project-management.run.java/plugin.js
apps/ide/src/plugins/webida.ide.project-management.run/delegator.js

* remove two unnecessary events named 
* 'webida.ide.project-management.run:configuration.hide' 
* 'webida.ide.project-management.run:configuration.show'

[TASK] (ODP-428) remove two unnecessary events

---

apps/ide/src/plugins/webida.ide.project-management.run.java/plugin.js
apps/ide/src/plugins/webida.ide.project-management.run/delegator.js
apps/ide/src/plugins/webida.ide.project-management.run/run-configuration-manager.js
apps/ide/src/plugins/webida.ide.project-management.run/view-controller.js

[BUGFIX] - ODP-457 The name of the run configuration changed according to path only when configuration hasn't been saved.
[IMPROVEMENT] Validation for the configuration's common required fields(name and target project) is handled by 'delegator' module (not by each plugin).

Bugfix and improvement on the Run Configuration Plugin

---

apps/ide/src/plugins/webida.ide.project-management.run/run-configuration.html

[BUGFIX] Add tooltip

---

apps/ide/src/plugins/webida.ide.project-management.run/style.css
apps/ide/src/plugins/webida.ide.project-management.run/view-controller.js

[DESC.]
- improve visibility of the tree view of run configuration window
- fix minor bugs on tree view

[BUGFIX][ENHANCEMENT] Fix #158 (ODP-438)

---

apps/ide/src/plugins/plugin-settings.json
apps/ide/src/plugins/webida.editor.test-editor/TestEditorPart.js
apps/ide/src/plugins/webida.editor.text-editor/TextEditorPart.js
apps/ide/src/plugins/webida.viewer.image-viewer/ImageEditorPart.js
apps/ide/src/plugins/webida.viewer.image-viewer/plugin.js
apps/ide/src/plugins/webida.viewer.image-viewer/plugin.json
apps/ide/src/plugins/webida.viewer.image-viewer/unit-test.js
common/src/webida/plugins/editors/plugin.js
common/src/webida/plugins/workbench/ui/Part.js
common/src/webida/plugins/workbench/ui/ViewPart.js

related issue : #150 
/cc @cimfalab

[feature] [#150] Image viewer plug-in

---

apps/ide/src/plugins/webida.ide.project-management.run.java/plugin.json

'Run As Java Application' -> 'Java Application'

[BUGFIX] fix type name of the Java as 'Java Application'

---

apps/ide/src/plugins/webida.editor.text-editor/TextEditorContext.js
common/src/webida/plugins/editors/editors-commands.js
common/src/webida/plugins/editors/plugin.js
common/src/webida/plugins/editors/workbench-panels.js

[DESC.] Removing direct codemirror access from editor-commands module.

[TASK] #177 Removing direct codemirror access from editor-commands

---

apps/ide/src/plugins/webida.editor.text-editor/TextEditorContext.js
common/src/webida/plugins/editors/plugin.js
common/src/webida/plugins/editors/viable-menu-items.js
common/src/webida/plugins/editors/workbench-shortcutList.js

[DESC.] Removing direct codemirror access from editor plugin modules.

[TASK] #177 Removing direct codemirror access from editors plugin

---

Gruntfile.js
bower.json
package.json

(cherry picked from commit ecb74de)

[TASK] Add grunt job for installing bower dependency.

---

apps/ide/src/plugins/webida.editor.code-editor/CodeEditorContext.js
apps/ide/src/plugins/webida.editor.text-editor/TextEditorContext.js
common/src/webida/plugins/editors/viable-menu-items.js

[DESC.] Removing direct codemirror access from viable-menu-items module.

[TASK] #177 Removing direct codemirror access from viable menu items

---

common/src/webida/plugins/workspace/Node.js
common/src/webida/plugins/workspace/plugin.js

If you enter space several times for renaming the project name, it doesn't represent &nbsp properly.

[BugFix] #204 issue for project name

---

apps/ide/src/plugins/webida.editor.code-editor/CodeEditorContext.js
apps/ide/src/plugins/webida.editor.text-editor/TextEditorContext.js
common/src/webida/plugins/editors/EditorContext.js

[DESC.] Initial EditorContext abstraction and hierarchy.

[TASK] #226 Initial EditorContext abstraction and hierarchy

---

common/src/webida/plugins/workspace/plugin.js
common/src/webida/webida-0.3.js
common/src/webida/webida-1.0.js

[DESC.]
- add filesystem API named "makeDnDDownloadUrl" for get a authorized(including token) download url at webida-0.3.js
- fix the wrong download url when user download only a file using drag and drop

[IMPROVEMENT & BUGFIX] (fix #175) refine drag & drop API and fix the download url

---

apps/ide/src/plugins/webida.editor.code-editor/CodeEditorViewer.js
apps/ide/src/plugins/webida.editor.code-editor/CodeMirrorAdapterForCodeEditor.js
apps/ide/src/plugins/webida.editor.text-editor/AceAdapterForTextEditor.js
apps/ide/src/plugins/webida.editor.text-editor/CodeMirrorAdapterForTextEditor.js
apps/ide/src/plugins/webida.editor.text-editor/TextEditorViewer.js
common/src/webida/plugins/editors/workbench-panels.js
common/src/webida/plugins/workbench/views-controller.js

[DESC.] Resize polling mechanism for editor is removed.

[TASK] #162 Editor resizing related refactoring

---

apps/ide/src/plugins/webida.editor.code-editor/CodeEditorViewer.js
apps/ide/src/plugins/webida.editor.text-editor/TextEditorViewer.js

[DESC.] No resizing bug for closing split editors is fixed.

[TASK] #162 Editor resizing related refactoring - (bug fix)

---

apps/ide/src/plugins/webida.workspace.model.file/File.js
apps/ide/src/plugins/webida.workspace.model.file/FileDataSource.js
common/src/webida/plugins/editors/EditorManager.js
common/src/webida/plugins/editors/plugin.js
common/src/webida/plugins/workbench/ui/DataSource.js
common/src/webida/plugins/workbench/ui/EditorAdpater.js
common/src/webida/plugins/workbench/ui/LayoutPane.js
common/src/webida/plugins/workbench/ui/LayoutTree.js
common/src/webida/plugins/workbench/ui/PartContainer.js
common/src/webida/plugins/workbench/ui/PartModel.js
common/src/webida/plugins/workbench/ui/PartRegistry.js
common/src/webida/plugins/workbench/ui/TabPartContainer.js
common/src/webida/plugins/workbench/ui/WidgetAdapter.js
common/src/webida/plugins/workbench/ui/Workbench.js
common/src/webida/plugins/workbench/ui/doc/Parts.uml

[TASK] EditorsManager.js -> EditorManager.js	b1c645f
[TASK] getters added to prevent direct variable access	cb7d2b0
[TASK] DataSource's getters for title, tooltip, titleImage added	fac792c
[TASK] EditorManager's requestOpen() updated.	27e92b7
[TASK] LayoutTree.js : getChildById() added	11d2639
[TASK] PartRegistry.js : getPartsByClassName() added	784aef5
[TASK] Workbench.js : parseModel() updated	aa377a0
[TASK] Parts.uml updated	6e44e55
[TASK] EditorAdpater, PartModel, WidgetAdapter added

[TASK] Workbench system updated

---

apps/ide/src/plugins/webida.notification/notification-message.js

[164] fixed bug in notification view

---

apps/ide/src/plugins/webida.editor.code-editor/CodeEditorViewer.js
apps/ide/src/plugins/webida.editor.text-editor/TextEditorPart.js
apps/ide/src/plugins/webida.editor.text-editor/TextEditorViewer.js
common/src/webida/plugins/workbench/views-controller.js

[DESC.] Re-sizing is modified to occur after layout change of top dojo BorderContainer of views-controller.

[BUGFIX] #162 #301 Editor re-sizing related refactoring (Bug fix)

---

common/src/webida/plugins/editors/workbench-panels.js

File>Close>Save and Close does not work #287

---

common/src/webida/plugins/editors/workbench-panels.js

#287 File>Close>Save and Close does not work

---

common/src/webida/plugins/workbench/views-controller.js
common/src/webida/widgets/views/splitviewcontainer.js

[DESC.] '#317 Editors are not re-sized for size changes within the editor area' is fixed.

[BUGFIX] #162 Editor resizing related refactoring (bug fix)

---

common/src/webida/plugins/fs-commands/plugin.js
common/src/webida/plugins/fs-commands/plugin.json
common/src/webida/plugins/workspace/plugin.js

[BUGFIX] Implement three toolbar item enable/disable procedure again.

---

apps/ide/src/plugins/webida.editor.code-editor/CodeEditorViewer.js
apps/ide/src/plugins/webida.editor.example.multi-viewer/FormEditorViewer.js
apps/ide/src/plugins/webida.editor.example.multi-viewer/MultiViewerExampleEditorPart.js
apps/ide/src/plugins/webida.editor.text-editor/TextEditorViewer.js
common/src/webida/plugins/workbench/ui/MultiViewerEditorPart.js
common/src/webida/plugins/workbench/ui/Viewer.js

[Desc.]
1) getContainerElement() -> getParentNode()
2) setContainerElement() -> setParentNode()

[TASK] Viewer's setter and getter name for parent node changed

---

apps/ide/src/plugins/webida.editor.code-editor/CodeEditorViewer.js
apps/ide/src/plugins/webida.editor.example.multi-viewer/FormEditorViewer.js
apps/ide/src/plugins/webida.editor.example.multi-viewer/MultiViewerExampleEditorPart.js
apps/ide/src/plugins/webida.editor.text-editor/AceAdapterForTextEditor.js
apps/ide/src/plugins/webida.editor.text-editor/CodeMirrorAdapterForTextEditor.js
apps/ide/src/plugins/webida.editor.text-editor/TextEditorPart.js
apps/ide/src/plugins/webida.editor.text-editor/TextEditorViewer.js
common/src/webida/plugins/workbench/ui/Viewer.js

1) create() -> createAdapter()
2) destroy() -> destroyAdapter()
3) setModel() -> setContents() 
4) getModel() -> getContents()

[TASK] Viewer method changed

---

apps/ide/src/plugins/webida.editor.example.multi-viewer/MultiViewerExampleEditorPart.js
apps/ide/src/plugins/webida.editor.text-editor/TextEditorPart.js
common/src/webida/plugins/workbench/ui/MultiViewerEditorPart.js
common/src/webida/plugins/workbench/ui/Part.js
common/src/webida/plugins/workbench/ui/doc/Parts.uml

1) MultiViewerEditorPart.js : addViewer() gets callback parameter
2) Part.js : setModel(model), getModel() added
3) Part.js : createViewer() added

[TASK] MultiViewerEditorPart.js, Part.js modified

---

apps/ide/src/plugins/webida.editor.example.multi-viewer/MultiViewerExampleEditorPart.js
common/src/webida/plugins/workbench/ui/MultiViewerEditorPart.js

1) MultiViewerEditorPart.js : setContainerEvent() added.
2) MultiPageExampleEditorPart.js : order of addViewer() changed.

[TASK] MultiViewerEditorPart.js, MultiPageExampleEditorPart.js

---

apps/ide/src/plugins/webida.editor.example.multi-viewer/FormEditorViewer.js
apps/ide/src/plugins/webida.editor.example.multi-viewer/MultiViewerExampleEditorPart.js
apps/ide/src/plugins/webida.editor.text-editor/TextEditorViewer.js
common/src/webida/plugins/editors/plugin.js
common/src/webida/plugins/workbench/ui/MultiViewerEditorPart.js
common/src/webida/plugins/workspace/plugin.js

[BUGFIX] Icon path resolution failed in case of dojoConfig cacheBust
[BUGFIX] Source editor is not displayed in mulitple tab editor (#326)
[TASK] Context menu example for MultiViewerEditorPart

[TASK] Icon path resolution, Source editor and Context menu for MultiViewerEditorPart

---

apps/ide/src/plugins/webida.editor.code-editor/CodeEditorViewer.js
apps/ide/src/plugins/webida.editor.example.multi-viewer/FormEditorAdpater.js
apps/ide/src/plugins/webida.editor.example.multi-viewer/FormEditorViewer.js
apps/ide/src/plugins/webida.editor.example.multi-viewer/MultiViewerExampleEditorPart.js
apps/ide/src/plugins/webida.editor.text-editor/Document.js
apps/ide/src/plugins/webida.editor.text-editor/TextEditorViewer.js
common/src/webida/plugins/editors/plugin.js
common/src/webida/plugins/workbench/ui/Viewer.js
common/src/webida/plugins/workbench/ui/WidgetAdapter.js
common/src/webida/plugins/workbench/ui/doc/Parts.uml

1) Saving MultiViewerEditorPart (But should be refactored, because of the editors plugin)
2) Viewer.js createAdapter() now accepts parentNode as a parameter

[TASK] Saving MultiViewerEditorPart

---

apps/ide/src/plugins/webida.ide.project-management.run/plugin.js
apps/ide/src/plugins/webida.ide.project-management.run/view-controller.js

[DESC.] runConfigurationManager.getByProjectName return value changes in key/value array from an array of objects. So I fixed to get the first index of an object.
Signed-off-by: ChangHyun Lee <leechwin.lee@samsung.com>

[BUGFIX] fix getting the first index of an object

---

common/src/webida/plugins/fs-commands/fs-commands.js

[BUGFIX] remove ':' at Go to File dialog. #298

---

apps/ide/src/plugins/webida.ide.project-management.run/layout/default-run-configuration.html

[DESC.]
This change includes the following changes.
- 'Window open arguments' changed to 'Window Features' via WHATWG specs
- 'Live reload' changed to 'Live Reload'
- Tooltips added for 'Window Features' and 'Live Reload'

[TASK] Refine labels and tooltips for 'General Web Application' settings

---

common/src/webida/widgets/views/viewcontainer.js

[BUGFIX] on pressing 'X' button, it doesn't work properly

---

apps/ide/src/plugins/webida.editor.code-editor/content-assist/goto-link.js
apps/ide/src/plugins/webida.editor.example.multi-viewer/MultiViewerExampleEditorPart.js
apps/ide/src/plugins/webida.editor.text-editor/TextEditorPart.js
apps/ide/src/plugins/webida.editor.text-editor/TextEditorViewer.js
common/src/webida/plugins/editors/editors-commands.js
common/src/webida/plugins/editors/plugin.js
common/src/webida/plugins/editors/workbench-panels.js
common/src/webida/plugins/workbench/ui/doc/Parts.uml
common/src/webida/widgets/views/viewcontainer.js

1) misspelt word deprcated -> deprecated
2) editors.openFile() --> topic.publish('#REQUEST.openFile')
3) file.savedValue --> file.getContents()

[TASK] editors updated

---

apps/ide/src/plugins/webida.ide.project-management.run/layout/default-run-configuration.html
apps/ide/src/plugins/webida.ide.project-management.run/run-configuration-manager.js

[DESC.]
Related with https://github.com/webida/webida-client/pull/355.
Combining the labels and symbols.
Signed-off-by: ChangHyun Lee <leechwin.lee@samsung.com>

[TASK] Refine labels for 'General Web Application' settings

---

common/src/webida/plugins/git/git-commands.js
common/src/webida/widgets/dialogs/buttoned-dialog/ButtonedDialog.js

[ENHANCEMENT] #295 Making dialog with ESC key

---

apps/desktop/settingsdlg.html

[DESC.]
Currently, the input label is just displayed "Gravatar email".
'Gravatar' is a service for avatar but some users do not know it.
So I append a label for the service and link to the Gravatar site.

[TASK] Add label for Gravatar service

---

apps/ide/src/plugins/project-configurator/project-info-service.js

[TASK] Add project info service (API)

---

common/src/webida/plugins/workspace/plugin.js

when 'ctrl+c', 'ctrl+x', and 'ctrl+v' is pressed sequentially at the workspace, plz make a new file in the manner of duplicating.

[ENHANCEMENT] #299 Changing 'ctrl+c', 'ctrl+x', and 'ctrl+v' action at the workspace

---

apps/site/pages/home.html

[TASK] Update demo movie

---

common/src/webida/plugins/git/git-commands.js

At workspace selecting some files and then doing 'git untrack'. then untracked a single file only.

[BUGFIX](#388) Git untrack for multi-selection

---

common/src/webida/plugins/git/git-commands.js

[TASK] forEach is changed to array map

---

apps/site/index.html
apps/site/pages/guest.html
apps/site/src/css/guest.css
apps/site/src/css/site.css
apps/site/src/js/guest.js
apps/site/src/js/main.js
apps/site/src/js/router.js
apps/site/src/js/util.js
common/src/webida/webida-0.3.js
common/src/webida/webida-1.0.js

- Write login UI of the guest mode
- Write actions for guest mode

[FEATURE] Guest Mode

---

common/src/webida/plugins/workspace/plugin.js

[DESC.] Continued from #203, project type considering feature will be added.

[FEATURE] (#383) Considering project type for resource icons

---

common/src/webida/plugins/editors/editors-commands.js
common/src/webida/plugins/editors/plugin.js
common/src/webida/plugins/editors/viable-menu-items.js

* viable-menu-items.js should be refactored
* Part should have their own way to contribute all kinds of menu.
Such as, context menu, global menu. This should be considered
next release.

[BUGFIX] Global Menu for new EditorPart

---

apps/monitor/src/css/monitor.css
bower.json

- fixed invalid value in bower.json
- changed view ratio between left and right.
Change-Id: I5d99ffee7386d07772fe368f2a462568c6f5f7dc
Signed-off-by: dy111.kim <dy111.kim@samsung.com>

[BUGFIX] fixed invalid values in bower.json

---

apps/ide/src/plugins/webida.editor.text-editor/TextEditorPart.js
apps/ide/src/plugins/webida.workspace.model.file/FileDataSource.js
common/src/webida/plugins/editors/plugin.js
common/src/webida/plugins/editors/workbench-panels.js
common/src/webida/plugins/workbench/ui/Part.js

This PR includes
[TASK] FileDataSource : publishes 'data-source/written' topic
[TASK] Recovering editors on load : wait 1sec
[TASK] Part : shows error's stack when exception occured
[TASK] Rebuild TextEditor's common preferences

[TASK] TextEditor's common preferences and others

---

apps/ide/src/plugins/webida.preference/plugin.js
apps/ide/src/plugins/webida.preference/preference-manager.js
apps/ide/src/plugins/webida.preference/services/preference-service.js
apps/ide/src/plugins/webida.preference/services/project-preference-service.js

[DESC.]
- add `preference/load` to the `promiseMap`
related with #460

[TASK] Use promiseMap at the preference plugin

---

apps/ide/src/plugins/webida.editor.code-editor/CodeEditorPart.js
apps/ide/src/plugins/webida.editor.text-editor/TextEditorPart.js
apps/ide/src/plugins/webida.preference/services/preference-service.js
apps/ide/src/plugins/webida.preference/services/project-preference-service.js
common/src/webida/plugins/editors/EditorPreference.js
common/src/webida/plugins/git/git-commands-diff.js
common/src/webida/plugins/workbench/command-system/MenuItemTree.js

- and add methods `preferenceService.setValue(s)`

[BUGFIX] make to use new `preferenceService` instead of `store` in workbench plugin

---

common/src/webida/FSCache-0.1.js
common/src/webida/webida-0.3.js
common/src/webida/webida-1.0.js

The server-side API still hasn't been ready.

[FEATURE] add FS API `replace`

---

apps/ide/src/plugins/webida.editor.code-editor/CodeEditorViewer.js
apps/ide/src/plugins/webida.editor.text-editor/TextEditorViewer.js

[DESC.] Theme applying problem is fixed.

[BUGFIX](#455)Theme is not applied to firstly opened editor.

---

apps/ide/src/plugins/webida.ide.search-result/search-result-model.js
apps/ide/src/plugins/webida.ide.search-result/search-result-view.js

Make that a search result item can be go to line with enter key.

[FEATURE](#499) go to line with enter key

---

apps/ide/src/plugins/webida.editor.text-editor/TextEditorViewer.js
apps/ide/src/plugins/webida.editor.text-editor/search-addon.js

[DESC.] Adding setHighlight method to TextEditorViewer for search result view.

[FEATURE](#515) Adding setHighlight method to TextEditorViewer

---

apps/ide/src/plugins/webida.ide.search-result/search-result-model.js
apps/ide/src/plugins/webida.ide.search-result/search-result-view.js
common/src/webida/widgets/checkbox-tree/CheckBoxTree.js

[FEATURE](#520) Making that a search result item highlight

---

apps/ide/src/plugins/webida.ide.search-result/search-result-controller.js
apps/ide/src/plugins/webida.ide.search-result/search-result-data.js
apps/ide/src/plugins/webida.ide.search-result/search-result-model.js
apps/ide/src/plugins/webida.ide.search-result/search-result-view.js
common/src/webida/widgets/checkbox-tree/CheckBoxTree.js

Making that a search result replace checked item only.

[FEATURE](#522) replace checked item only

---

apps/ide/src/plugins/uid-menu-items/plugin.js
common/src/webida/app-config.js
common/src/webida/plugins/git/git-commands.js

and webida-client app also changed too (-> 'ide.*')

[TASK] change default sub domain of dashboard app from 'dashboard' to ''

---

apps/ide/src/plugins/webida.ide.search-result/search-result-model.js

Abnormal search for '/ base dir' in 'Search result view'

[BUGFIX](#507) Abnormal search for '/ base dir' in 'Search result view'

---

common/src/webida/FSCache-0.1.js
common/src/webida/plugins/git/git-icon.js
common/src/webida/plugins/git/plugin.json

Abnormal untrack status for mixed reset files

[BUGFIX](#512) Abnormal untrack status for mixed reset files

---

apps/ide/src/plugins/webida.ide.search-result/README.md

Documentation on search result plugin

[DOCUMENT](#567) search result plugin

---

common/src/webida/plugins/editors/plugin.json
common/src/webida/plugins/fs-commands/plugin.json
common/src/webida/plugins/output/style/output.css
common/src/webida/plugins/workbench/command-system/toolbar.js
common/src/webida/plugins/workbench/plugin.json

Signed-off-by: ChangGyun Woo <cg25.woo@samsung.com>

[BUGFIX]Change toolbar image path

---

apps/ide/src/plugins/webida.editor.code-editor.content-assist.tern/README.md
apps/ide/src/plugins/webida.editor.code-editor.content-assist.tern/TernControl.js
apps/ide/src/plugins/webida.editor.code-editor.content-assist.tern/tern-server-starter.js
apps/ide/src/plugins/webida.editor.code-editor/CodeEditorContextMenu.js
apps/ide/src/plugins/webida.editor.code-editor/CodeEditorViewer.js
apps/ide/src/plugins/webida.editor.code-editor/README.md
apps/ide/src/plugins/webida.editor.code-editor/content-assist/ContentAssistDelegator.js
apps/ide/src/plugins/webida.editor.code-editor/content-assist/IContentAssist.js
apps/ide/src/plugins/webida.editor.code-editor/content-assist/assist.js

[DESC.] Tern content assist plugin for multiple content assist support (Refactoring 1).

[FEATURE](#545) Tern content assist plugin (Refactoring 1)

---

apps/ide/src/plugins/webida.editor.code-editor.content-assist.calcium/CalciumControl.js
apps/ide/src/plugins/webida.editor.code-editor.content-assist.calcium/README.md
apps/ide/src/plugins/webida.editor.code-editor.content-assist.calcium/calcium-server.js
apps/ide/src/plugins/webida.editor.code-editor.content-assist.calcium/calcium.js
apps/ide/src/plugins/webida.editor.code-editor.content-assist.calcium/plugin.js
apps/ide/src/plugins/webida.editor.code-editor.content-assist.calcium/plugin.json
apps/ide/src/plugins/webida.editor.code-editor/content-assist/ContentAssistDelegator.js
bower.json

Please review. Any comments will be welcome.

Calcium plugin

---

apps/ide/src/dojoConfig.js
apps/ide/src/plugins/plugin-settings-guest.json
apps/ide/src/plugins/plugin-settings.json
apps/ide/src/plugins/webida.locale/README.md
apps/ide/src/plugins/webida.locale/locale-handler.js
apps/ide/src/plugins/webida.locale/locale-preference.js
apps/ide/src/plugins/webida.locale/nls/en-us/resource.js
apps/ide/src/plugins/webida.locale/nls/resource.js
apps/ide/src/plugins/webida.locale/nls/zh-cn/resource.js
apps/ide/src/plugins/webida.locale/plugin.js
apps/ide/src/plugins/webida.locale/plugin.json

Support locale-sensitive languages.

[FEATURE](#575) Support i18n & l10n

---

common/src/webida/FSCache-0.1.js
common/src/webida/util/path.js

- FSCache should be able to write files in workspace root
- util/path.js should not chop '/' to '' to handle root directory

[BUGFIX] git configure spits error

---

apps/ide/src/styles/css/ContentPane.css
apps/ide/src/styles/css/TabContainer.css
apps/ide/src/styles/layout/ContentPane.less
apps/ide/src/styles/layout/TabContainer.less
common/src/webida/plugins/editors/themes/webida-dark.css

*  Workspace issue - [[BUGFIX]Reduce page height to fit #73](https://github.com/webida/webida-dashboard/issues/71)

[BUGFIX]update tabcontainer stylesheet - OPTC-71

---

apps/ide/src/plugins/help/help-commands.js

[TASK] change help document contents

---

apps/ide/src/plugins/webida.editor.code-editor/content-assist/assist-worker.js

[DESC.] Exception handlings for assist-worker message handlings are added.

[BUGFIX](#617) Exception handlings for assist-worker message handlings.

---

apps/ide/src/plugins/help/help-commands.js

[BUGFIX] help contents link

---

apps/ide/src/plugins/webida.ide.notification.view/notification.js
apps/ide/src/plugins/webida.ide.notification.view/style/style.css

Apply for the type labeling such as the appearance of a label

---

common/src/webida/plugins/output/layer/_tmplToolbar.html
common/src/webida/plugins/output/nls/en-us/resource.js
common/src/webida/plugins/output/nls/resource.js
common/src/webida/plugins/output/nls/zh-cn/resource.js
common/src/webida/plugins/output/plugin.js
common/src/webida/util/locale.js

- convert message support.
- applied to output plugin.

[FEATURE](#575) Support i18n in output plugin.

---

common/src/webida/plugins/preview/handler/html.js
common/src/webida/plugins/preview/handler/image.js
common/src/webida/plugins/preview/layout/preview-toolbar.html
common/src/webida/plugins/preview/nls/en-us/resource.js
common/src/webida/plugins/preview/nls/resource.js
common/src/webida/plugins/preview/nls/zh-cn/resource.js
common/src/webida/plugins/preview/preview-commands.js
common/src/webida/plugins/preview/preview-pref-page.js
common/src/webida/plugins/preview/preview-view.js

[FEATURE](#575) support i18n in preview plugin

---

common/src/webida/FSCache-0.1.js
common/src/webida/plugins/git/git-commands.js
common/src/webida/util/path.js

- reverted commit 01c264b
- changed .gitmessage file location from / to /.userinfo
- also fixed tab indentations (sorry for my .vimrc missing .js file type to apply soft tab stop) 
thx cho.

[BUGFIX] fix #637

---

common/src/webida/app-config.js

[TASK] change default client ID for new server installation method.

---

apps/ide/src/plugins/uid-menu-items/nls/en-us/resource.js
apps/ide/src/plugins/uid-menu-items/nls/resource.js
apps/ide/src/plugins/uid-menu-items/nls/zh-cn/resource.js
apps/ide/src/plugins/uid-menu-items/plugin.js
apps/ide/src/plugins/webida.ide.search-result/layout/search-result.html
apps/ide/src/plugins/webida.ide.search-result/nls/en-us/resource.js
apps/ide/src/plugins/webida.ide.search-result/nls/resource.js
apps/ide/src/plugins/webida.ide.search-result/nls/zh-cn/resource.js
apps/ide/src/plugins/webida.ide.search-result/search-result-view.js

support i18n in search-result plugin
support i18n in uid-menu-items plugin.

[FEATURE](#575) Support i18n in search-result plugin, uid-menu-items plugin.

---

common/src/webida/plugins/preview/nls/en-us/resource.js

[TASK] Typo fixes

---

apps/ide/src/plugins/webida.locale/README.md

[DOCUMENT](#575) How to add language

---

apps/ide/src/plugins/webida.ide.search-result/style/search-result.css

Signed-off-by: ChangGyun Woo <cg25.woo@samsung.com>

[BUGFIX]update search view background

---

.jshintrc
Gruntfile.js
apps/dashboard/Gruntfile.js
apps/dashboard/src/js/services/App.js
apps/dashboard/src/js/services/ApplicationManager.js
apps/deploy/Gruntfile.js
apps/desktop/Gruntfile.js
apps/desktop/script/js/main.js
apps/monitor/src/js/left.js
apps/monitor/src/js/monitor-client.js
apps/monitor/src/js/monitor.js
apps/monitor/src/js/right.js
apps/monitor/src/js/right/pf-current-stat.js
apps/monitor/src/js/right/pf-current.js
apps/monitor/src/js/right/pf-statistics-history.js
apps/site/Gruntfile.js
apps/site/src/js/guest.js
apps/site/src/js/router.js

[DESC.] Fixed codes for code convention except IDE and common

[TASK] Fixed codes for code convention.

---

apps/ide/src/styles/css/webida-base.css

[DESC.] declear for font-family in css
Signed-off-by: ChangHyun Lee <leechwin.lee@samsung.com>

[BUGFIX] fix "Nanum Gothic Coding" font can not apply

---

apps/ide/src/plugins/webida.ide.project-management.run/style/style.css
apps/ide/src/plugins/webida.preference/style/style.css
apps/ide/src/styles/comp/Dialog.less
apps/ide/src/styles/comp/EnhancedGrid.less
apps/ide/src/styles/css/Dialog.css
apps/ide/src/styles/css/EnhancedGrid.css
apps/ide/src/styles/css/webida-base.css
apps/ide/src/styles/css/webida-project-wizard.css
apps/ide/src/styles/less/webida-base.less
common/src/webida/plugins/git/style/gitview.css
common/src/webida/plugins/workspace/style/wv.css

Css for dialog box looks strange #661
*Replace dialog theme
Signed-off-by: ChangGyun Woo <cg25.woo@samsung.com>

[IMPROVEMENT] Css for dialog box looks strange

---

apps/ide/src/plugins/plugin-settings-guest.json
apps/ide/src/plugins/plugin-settings.json
apps/ide/src/plugins/webida.editor.code-editor.content-assist.css.css-smart/CssSmartControl.js
apps/ide/src/plugins/webida.editor.code-editor.content-assist.css.css-smart/README.md
apps/ide/src/plugins/webida.editor.code-editor.content-assist.css.css-smart/css-hint-server.js
apps/ide/src/plugins/webida.editor.code-editor.content-assist.css.css-smart/css-hint.js
apps/ide/src/plugins/webida.editor.code-editor.content-assist.css.css-smart/plugin.js
apps/ide/src/plugins/webida.editor.code-editor.content-assist.css.css-smart/plugin.json
apps/ide/src/plugins/webida.editor.code-editor.content-assist.css.default/CssDefaultControl.js
apps/ide/src/plugins/webida.editor.code-editor.content-assist.css.default/README.md
apps/ide/src/plugins/webida.editor.code-editor.content-assist.css.default/plugin.js
apps/ide/src/plugins/webida.editor.code-editor.content-assist.css.default/plugin.json
apps/ide/src/plugins/webida.editor.code-editor/CodeEditorPart.js
apps/ide/src/plugins/webida.editor.code-editor/CodeEditorViewer.js
apps/ide/src/plugins/webida.editor.code-editor/content-assist/ContentAssistDelegator.js
apps/ide/src/plugins/webida.editor.code-editor/content-assist/assist-worker.js

[DESC.] Extracting CSS code assist engine from CodeEditorViewer to an individual plugins.

[IMPROVEMENT](#633)Extracting CSS code assist plugins

---

apps/ide/src/styles/comp/Dialog.less
apps/ide/src/styles/css/Dialog.css

[Css for popup #676](https://github.com/webida/webida-client/issues/676)
Signed-off-by: ChangGyun Woo <cg25.woo@samsung.com>

[BUGFIX]Css for popup

---

apps/ide/src/plugins/webida.ide.notification.view/layout/notification-preference.html
apps/ide/src/plugins/webida.ide.notification.view/nls/en-us/resource.js
apps/ide/src/plugins/webida.ide.notification.view/nls/resource.js
apps/ide/src/plugins/webida.ide.notification.view/notification-view.js
apps/ide/src/plugins/webida.ide.notification.view/preferences/NotificationPreferencePage.js

[DESC.] i18n for webida.ide.notification.view plugin

[FEATURE](#687) i18n for notification view plugin

---

common/src/webida/widgets/dialogs/buttoned-dialog/ButtonedDialog.js

[DESC.]
(1) The argument to a ButtonedDialog constructor can have an optional member "validateContent" which must be a function if present.
(2) Each button spec in the argument's 'buttons' array can have an optional member "reactToValidation" which must be either '+' or '-' if present.
(3) A button that reacts "positively" to the validation is enabled when the validateContent returns a truthy value and disabled when the return value is a falsy.
(4) A button that reacts "negatively" to the validation is disabled when the validateContent returns a truthy value and enabled when the return value is a falsy.

[FEATURE] Letting some buttons react to the result of a dialog's method "validateContent"

---

common/src/webida/plugins/workspace/Node.js
common/src/webida/plugins/workspace/layer/new-node.html
common/src/webida/plugins/workspace/nls/en-us/resource.js
common/src/webida/plugins/workspace/nls/resource.js
common/src/webida/plugins/workspace/plugin.js
common/src/webida/plugins/workspace/preference-workspace.js

[DESC.]
* i18n for workspace plugin
* webida-lib/plugins/workspace

[FEATURE] (#699) i18n for workspace plugin

---

apps/ide/src/plugins/webida.editor.text-editor/TextEditorViewer.js

Note that, this commit requires codemirror 5.5.0 or higher.
This will works after merging of codemirror folk with 5.5.0 above.

[BUGFIX] Abnormal dirty status for windows based files

---

apps/ide/src/plugins/webida.editor.code-editor.content-assist.calcium/calcium-server.js
apps/ide/src/plugins/webida.editor.code-editor.content-assist.calcium/calcium.js

[DESC.] The file-server does not serve the contents in the editors. So, I could not use file-server and made a simple analysis cache in calcium-server.

[IMPROVEMENT] Cache analysis result computed by calcium #445

---

common/src/webida/util/locale.js

[DESC.]
- enabling to initialize `Locale` object with the resource object
- add `convertMessage` and `formatMessage` methods that can be resource-based run

[IMPROVEMENT] enhance functionality of locale util

---

common/src/webida/util/locale.js

[DESC.]
- add `convertMenuItem` method for applying i18n on menu items
- let `formatMessage` run in more safe way

[IMPROVEMENT] Improve functionality on locale util

---

apps/ide/src/plugins/help/about.html
apps/ide/src/plugins/help/help-commands.js
apps/ide/src/plugins/help/nls/en-us/resource.js
apps/ide/src/plugins/help/nls/resource.js
apps/ide/src/plugins/help/plugin.js
apps/ide/src/plugins/project-wizard/layer/pw-layout.html
apps/ide/src/plugins/project-wizard/nls/en-us/resource.js
apps/ide/src/plugins/project-wizard/nls/resource.js
apps/ide/src/plugins/project-wizard/plugin.js
apps/ide/src/plugins/project-wizard/pw-commands.js

I18N misc - help & project wizard

---

common/src/webida/plugins/workbench/command-system/MenuItemTree.js
common/src/webida/plugins/workbench/command-system/command-list/cl-commands.js
common/src/webida/plugins/workbench/nls/en-us/resource.js
common/src/webida/plugins/workbench/nls/resource.js

[DESC.] i18n for notifications in workspace plugin

[FEATURE] (#699) i18n for notifications in workspace plugin

---

common/src/webida/plugins/workbench/command-system/MenuItemTree.js
common/src/webida/plugins/workbench/command-system/command-list/cl-commands.js

[DESC.] Invalid i18n resource path

[BUGFIX] (#699) Invalid i18n resource path

---

apps/ide/src/plugins/help/help-commands.js

[DESC.]
Now 'Help -> About' dialog will show up.
Related to OPTC-64.
Note that in the dialog, the version number is still 1.5.0 which is hard-coded.
@kyungmi will fix the version number when we release 1.6.0.

[BUGFIX] Fix wrong path for package.json

---

common/src/webida/plugins/workbench/command-system/MenuItemTree.js
common/src/webida/plugins/workbench/command-system/command-list/cl-commands.js
common/src/webida/plugins/workbench/command-system/shortcutKeysDlg.js
common/src/webida/plugins/workbench/nls/en-us/resource.js
common/src/webida/plugins/workbench/nls/resource.js
common/src/webida/plugins/workbench/ui/editorDialog.js
common/src/webida/plugins/workbench/workspaceSelectionDialog.js

[DESC.] i18n for dialogs in workbench plugin

[FEATURE] (#668) i18n for dialogs in workbench plugin

---

apps/ide/src/plugins/webida.editor.text-editor/TextEditorViewer.js

[BUGFIX] (#689) goto line not work

---

common/src/webida/plugins/git/git-commands.js

[BUGFIX](#769) Fixed git command for 'git reset --hard'

---

apps/ide/src/plugins/plugin-settings-guest.json
apps/ide/src/plugins/plugin-settings.json
apps/ide/src/plugins/webida.editor.code-editor.content-assist.comments/CommentsControl.js
apps/ide/src/plugins/webida.editor.code-editor.content-assist.comments/README.md
apps/ide/src/plugins/webida.editor.code-editor.content-assist.comments/plugin.js
apps/ide/src/plugins/webida.editor.code-editor.content-assist.comments/plugin.json
apps/ide/src/plugins/webida.editor.code-editor/CodeEditorContextMenu.js
apps/ide/src/plugins/webida.editor.code-editor/CodeEditorViewer.js

[DESC.] Refactoring comment related code for code-editor into a new content assist plugin

[IMPROVEMENT](#780) Refactoring comment related code for code-editor

---

apps/ide/src/plugins/plugin-settings-guest.json
apps/ide/src/plugins/plugin-settings.json
apps/ide/src/plugins/webida.editor.code-editor.content-assist.beautify/BeautifyControl.js
apps/ide/src/plugins/webida.editor.code-editor.content-assist.beautify/README.md
apps/ide/src/plugins/webida.editor.code-editor.content-assist.beautify/plugin.js
apps/ide/src/plugins/webida.editor.code-editor.content-assist.beautify/plugin.json
apps/ide/src/plugins/webida.editor.code-editor/CodeEditorViewer.js

[DESC.]
* Refactoring beautify related code for code-editor into a new beautify content assist plugin

[IMPROVEMENT](#794)Refactoring beautify related code for code-editor

---

Gruntfile.js

#760
[DESC.]
- solve the problem `grunt` command is failed
- add the `compress: true` option to less task
- rename 'themeBuild' task to 'theme' (`grunt themeBuild` => `grunt theme`)
- refactoring on theme task logic and configuration

[BUGFIX] #760 refactor and fix bug on Gruntfile.js

---

common/src/webida/plugins/workbench/command-system/MenuItemTree.js
common/src/webida/plugins/workbench/nls/en-us/resource.js
common/src/webida/plugins/workbench/nls/resource.js
common/src/webida/plugins/workbench/plugin.js
common/src/webida/plugins/workbench/wb-commands.js

[DESC.] i18n for alerts in workbench plugin

[FEATURE] (#668) i18n for alerts in workbench plugin

---

apps/ide/src/plugins/webida.editor.code-editor/lib/acorn/dist/acorn.js
apps/ide/src/plugins/webida.editor.code-editor/lib/acorn/dist/acorn_csp.js
apps/ide/src/plugins/webida.editor.code-editor/lib/acorn/dist/acorn_loose.js
apps/ide/src/plugins/webida.editor.code-editor/lib/acorn/dist/walk.js

[DESC.] This commit uploads the compiled modules of acorn-2.6.4.
I needed a small patch for acorn-2.6.4 to generate proper AMD modules,
which you can find at https://github.com/happibum/acorn/commit/cbbee69df16e8150f3243b088a3a633fc5046606
Please ignore coding style problems. 
All the files are external and compiled modules.

[TASK] Update acorn used by tern to the recent version (#819).

---

apps/ide/src/plugins/webida.ide.search-result/search-result-view.js

- add event handler for 'enter' key

[IMPROVEMENT](#610)Shortcut key(Enter) setting for find button in Search-result

---

apps/ide/src/plugins/webida.viewer.image-viewer/ImageEditorContextMenu.js
apps/ide/src/plugins/webida.viewer.image-viewer/ImageEditorPart.js

This solution is temporary.
Because current menu system does not support
Inheritance of menu hierarchy
This commit will be refactored in the future with new menu system.

[TASK] Contex menu for image viewer

---

apps/ide/src/plugins/webida.locale/locale-handler.js
apps/ide/src/plugins/webida.locale/locale-preference.js

- add JsDoc for public methods

[DOCUMENT](#773)Jsdoc for sources in locale plugin.

---

apps/ide/src/plugins/webida.ide.search-result/search-result-controller.js
apps/ide/src/plugins/webida.ide.search-result/search-result-data.js
apps/ide/src/plugins/webida.ide.search-result/search-result-model.js
apps/ide/src/plugins/webida.ide.search-result/search-result-view.js

- add JsDoc for public methods
- change the name of the method

DOCUMENT](#773)Jsdoc for sources in serach-result plugin.

---

common/src/webida/plugins/preview/handler/html.js
common/src/webida/plugins/preview/handler/image.js

[BUG](#766) Preview of image file is not working.

---

common/src/webida/plugins/preview/preview-menu-item.js

- add defensive code
- fix return type

[BUG](#838)Workspace context menu spits out an error.

---

common/src/webida/plugins/git/git-commands.js

[BUGFIX] toast message key change

---

apps/ide/src/plugins/webida.ide.project-management.run/delegator.js
apps/ide/src/plugins/webida.ide.project-management.run/plugin.js
apps/ide/src/plugins/webida.ide.project-management.run/view-controller.js
apps/ide/src/plugins/webida.ide.project.deploy/plugin.js
apps/ide/src/plugins/webida.plugin-setting/README.md
apps/ide/src/plugins/webida.plugin-setting/dialog-controller.js
apps/ide/src/plugins/webida.plugin-setting/plugin-settings.js
apps/ide/src/plugins/webida.plugin-setting/plugin.js

[DESC.]
- add JsDoc for public/private methods
- clean up code and its dependencies
- change the occurrences of `@returns` to `@return`

[DOCUMENT] (#772, #535) Documentation for plugin-settings plugin

---

apps/ide/src/plugins/webida.editor.code-editor.content-assist.comments/CommentsControl.js
apps/ide/src/plugins/webida.editor.code-editor.content-assist.comments/README.md
apps/ide/src/plugins/webida.editor.code-editor.content-assist.comments/plugin.js
apps/ide/src/plugins/webida.editor.code-editor/CodeEditorViewer.js

[DESC.] ineComment, blockComment, commentOutSelection are changed to plugin commands.

[BUGFIX](#861) Comments plugin refactoring

---

apps/ide/src/plugins/webida.preference/view-controller.js
common/src/webida/plugins/editors/themes/webida-dark.css
common/src/webida/plugins/editors/themes/webida-light.css

Currently register a handler to the "Restore" and "Appply" button for each page, and then handler is called multiple times.
So, i modified to register at the time of dialog creation.

[BUGFIX] Modify the duplicate listeners

---

apps/ide/src/plugins/webida.ide.search-result/layout/search-result.html
apps/ide/src/plugins/webida.ide.search-result/style/search-result.css
common/src/webida/plugins/git/git-commands.js
common/src/webida/plugins/git/layer/fetch.html
common/src/webida/plugins/git/layer/pull.html
common/src/webida/plugins/git/style/git-dialog.css
common/src/webida/plugins/workbench/command-system/MenuItemTree.js
common/src/webida/plugins/workbench/command-system/layer/shortcutKeysSettingDlg.html
common/src/webida/plugins/workbench/command-system/shortcutKeysDlg.js
common/src/webida/plugins/workbench/command-system/style/style.css
common/src/webida/widgets/dialogs/buttoned-dialog/ButtonedDialog.js

- change markup of the template
- Search result view, shortcut key dialog, git pull and git fetch are patched.

[BUGFIX] (#854) Prevent from chrome freezing

---

apps/ide/src/plugins/webida.editor.code-editor.content-assist.css.css-smart/css-hint-server.js
apps/ide/src/plugins/webida.editor.code-editor/CodeEditorContextMenu.js
apps/ide/src/plugins/webida.editor.code-editor/CodeEditorMenu.js

[DESC.] 
* Unresolved deffered problem for original solution of #828 is fixed.(Disabled menus for html files)
* No null check for css-smart request query is fixed.

[BUGFIX](#828)TypeError from css-hint-server.js on opening non-css files

---

common/src/webida/plugins/git/git-commands-diff.js
common/src/webida/plugins/git/git-commands.js
common/src/webida/plugins/git/git-core.js
common/src/webida/plugins/git/git-icon.js
common/src/webida/plugins/git/git-view.js
common/src/webida/plugins/git/gitview-log.js
common/src/webida/plugins/git/plugin.js
common/src/webida/plugins/git/preference-git.js

- add JSDoc for public methods
- change the name of methods

[DOCUMENT](#773) JSDoc for source in git plugin.

---

common/src/webida/plugins/git/git-commands-diff.js
common/src/webida/plugins/git/git-commands.js
common/src/webida/plugins/git/git-core.js
common/src/webida/plugins/git/git-icon.js
common/src/webida/plugins/git/git-view.js
common/src/webida/plugins/git/plugin.js
common/src/webida/plugins/git/preference-git.js

- separates the author
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/webida/webida-client/878)

[DOCUMENT](#773) JSDoc for source in git plugin

---

common/src/webida/plugins/workspace/Node.js
common/src/webida/plugins/workspace/plugin.js
common/src/webida/plugins/workspace/preference-workspace.js

- add JSDoc for public method
- change the name of method
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/webida/webida-client/879)

[DOCUMENT](#773) JSDoc for source in workspace plugin

---

Gruntfile.js
package.json

resolves #880  
- replaced grunt-bower to grunt-auto-install
- added excluding project wizard templates
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/webida/webida-client/881)

[IMPROVEMENT] support recursive bower install in running grunt

---

common/src/webida/plugins/workbench/command-system/context-menu.js

Context menu bug on dialog's text input with keyboard's popup key
- block key event
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/webida/webida-client/882)

[BUGFIX](#716)Context menu bug on dialog's text input with keyboard's

---

common/src/webida/plugins/workbench/command-system/context-menu.js

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/webida/webida-client/888)

[BUGFIX] typo error

---

apps/ide/src/plugins/webida.ide.project-management.run/style/style.css

- fixed style(margin)
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/webida/webida-client/886)

[BUGFIX](#884)Run configurations' behavior is weird

---

common/src/webida/plugins/workbench/command-system/toolbar.js

- fixed checking error for invisible item
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/webida/webida-client/908)

[BUGFIX] select toolbar items
